openapi: 3.0.0
info:
  title: Transactions API
  description: API pour gérer les transactions bancaires
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Serveur local

security:
  - BearerAuth: []

paths:
  /transactions:
    get:
      summary: Récupère toutes les transactions pour le mois en cours
      description: Retourne une liste de toutes les transactions pour le mois en cours, groupées par compte.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Une liste de transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non autorisé, token manquant ou invalide
        '500':
          description: Erreur serveur

    post:
      summary: Ajoute une nouvelle transaction
      description: Ajoute une nouvelle transaction à la base de données.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '201':
          description: Transaction créée avec succès
        '400':
          description: Requête invalide
        '401':
          description: Non autorisé, token manquant ou invalide

  /transactions/{id}:
    get:
      summary: Récupère les détails d'une transaction
      description: Retourne les détails d'une transaction spécifique.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Non autorisé, token manquant ou invalide
        '404':
          description: Transaction non trouvée

    patch:
      summary: Met à jour partiellement une transaction
      description: Met à jour partiellement les informations d'une transaction spécifique, comme la catégorie ou la note.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Catégorie de la transaction
                  example: "Food"
                note:
                  type: string
                  description: Note sur la transaction
                  example: "Achat de pain et pâtisseries"
      responses:
        '200':
          description: Transaction partiellement mise à jour avec succès
        '400':
          description: Requête invalide
        '401':
          description: Non autorisé, token manquant ou invalide
        '404':
          description: Transaction non trouvée

    delete:
      summary: Supprime une transaction
      description: Supprime une transaction spécifique de la base de données.
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      responses:
        '204':
          description: Transaction supprimée avec succès
        '401':
          description: Non autorisé, token manquant ou invalide
        '404':
          description: Transaction non trouvée

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: ID de la transaction
          example: "507f1f77bcf86cd799439011"
        accountId:
          type: string
          description: ID du compte
          example: "507f1f77bcf86cd799439012"
        amount:
          type: number
          description: Montant de la transaction
          example: 5.00
        balance:
          type: number
          description: Solde après la transaction
          example: 2084.60
        date:
          type: string
          format: date
          description: Date de la transaction
          example: "2020-06-20"
        description:
          type: string
          description: Description de la transaction
          example: "Golden Sun Bakery"
        category:
          type: string
          description: Catégorie de la transaction
          example: "Food"
        note:
          type: string
          description: Note sur la transaction
          example: "Achat de pain et pâtisseries"
